# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  mysql_host:
    default: mysql
    description: The hostname of the MySQL instance
    type: string

  mysql_port:
    default: 3306
    description: The port of the MySQL instance
    type: int

  mysql_user:
    default: root
    description: The user to access the MySQL instance
    type: string

  mysql_password:
    default: root_password
    description: The password to access the MySQL instance
    type: string
